### ISSUE TITLE
Details page rendering indefinitely 

### ISSUE THREAD

**Issue by PrashantSunwar** [SahasSaurav/react-rest-countries-api#1]
Details page rendering indefinitely.
I analyzed your code and what you have done is that you are relying on a deprecated lifecycle method componentWillUpdate() for change in border value which is causing an infinite render.
What you can do is use componentDidUpdate() for checking if the props are changed and then set the state.
For more details refer to this
https://bhch.github.io/posts/2019/04/how-to-fetch-data-or-update-state-when-a-route-changes-in-react-router/

**Comment by SahasSaurav** [comment]
Thanks for letting me know . I just to learn react this was frist project
build from react . Now i understand why chrome is sucking so much of ram....
I m really to you mate
